/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type BalconySize = { 'large' : null } |
  { 'small' : null } |
  { 'medium' : null };
export interface ConsultationRequest {
  'id' : bigint,
  'sunlightExposure' : SunlightExposure,
  'stylePreference' : StylePreference,
  'balconySize' : BalconySize,
  'name' : string,
  'email' : string,
  'message' : string,
  'timestamp' : Time,
  'phone' : [] | [string],
}
export type StylePreference = { 'tropical' : null } |
  { 'minimalist' : null } |
  { 'natural' : null } |
  { 'modern' : null };
export type SunlightExposure = { 'partialShade' : null } |
  { 'fullSun' : null } |
  { 'fullShade' : null };
export type Time = bigint;
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'getAllConsultationRequests' : ActorMethod<[], Array<ConsultationRequest>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getConsultationRequestCount' : ActorMethod<[], bigint>,
  'getConsultationRequestCountAdmin' : ActorMethod<[], bigint>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'submitConsultationRequest' : ActorMethod<
    [
      string,
      string,
      [] | [string],
      BalconySize,
      SunlightExposure,
      StylePreference,
      string,
    ],
    boolean
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];