/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const SessionInfo = IDL.Record({
  'timezone' : IDL.Text,
  'loginTime' : IDL.Int,
  'token' : IDL.Text,
  'ipHint' : IDL.Text,
  'deviceInfo' : IDL.Text,
});
export const Status = IDL.Variant({
  'new' : IDL.Null,
  'completed' : IDL.Null,
  'inProgress' : IDL.Null,
});
export const SunlightExposure = IDL.Variant({
  'partialShade' : IDL.Null,
  'fullSun' : IDL.Null,
  'fullShade' : IDL.Null,
});
export const StylePreference = IDL.Variant({
  'tropical' : IDL.Null,
  'minimalist' : IDL.Null,
  'natural' : IDL.Null,
  'modern' : IDL.Null,
});
export const BalconySize = IDL.Variant({
  'large' : IDL.Null,
  'small' : IDL.Null,
  'medium' : IDL.Null,
});
export const Time = IDL.Int;
export const Priority = IDL.Variant({
  'low' : IDL.Null,
  'high' : IDL.Null,
  'medium' : IDL.Null,
});
export const ConsultationRequest = IDL.Record({
  'id' : IDL.Nat,
  'status' : Status,
  'sunlightExposure' : SunlightExposure,
  'stylePreference' : StylePreference,
  'balconySize' : BalconySize,
  'name' : IDL.Text,
  'email' : IDL.Text,
  'message' : IDL.Text,
  'timestamp' : Time,
  'priority' : Priority,
  'phone' : IDL.Opt(IDL.Text),
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'blockSession' : IDL.Func([IDL.Text], [IDL.Bool], []),
  'deleteConsultationRequest' : IDL.Func([IDL.Nat], [IDL.Bool], []),
  'getAllAdminSessions' : IDL.Func([], [IDL.Vec(SessionInfo)], ['query']),
  'getAllConsultationRequests' : IDL.Func(
      [],
      [IDL.Vec(ConsultationRequest)],
      ['query'],
    ),
  'getBlockedSessions' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getConsultationRequestCount' : IDL.Func([], [IDL.Nat], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'isSessionBlocked' : IDL.Func([IDL.Text], [IDL.Bool], ['query']),
  'registerAdminSession' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [IDL.Bool],
      [],
    ),
  'removeAdminSession' : IDL.Func([IDL.Text], [IDL.Bool], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'submitConsultationRequest' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        IDL.Opt(IDL.Text),
        BalconySize,
        SunlightExposure,
        StylePreference,
        IDL.Text,
      ],
      [IDL.Bool],
      [],
    ),
  'unblockSession' : IDL.Func([IDL.Text], [IDL.Bool], []),
  'updateRequestPriority' : IDL.Func([IDL.Nat, Priority], [IDL.Bool], []),
  'updateRequestStatus' : IDL.Func([IDL.Nat, Status], [IDL.Bool], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const SessionInfo = IDL.Record({
    'timezone' : IDL.Text,
    'loginTime' : IDL.Int,
    'token' : IDL.Text,
    'ipHint' : IDL.Text,
    'deviceInfo' : IDL.Text,
  });
  const Status = IDL.Variant({
    'new' : IDL.Null,
    'completed' : IDL.Null,
    'inProgress' : IDL.Null,
  });
  const SunlightExposure = IDL.Variant({
    'partialShade' : IDL.Null,
    'fullSun' : IDL.Null,
    'fullShade' : IDL.Null,
  });
  const StylePreference = IDL.Variant({
    'tropical' : IDL.Null,
    'minimalist' : IDL.Null,
    'natural' : IDL.Null,
    'modern' : IDL.Null,
  });
  const BalconySize = IDL.Variant({
    'large' : IDL.Null,
    'small' : IDL.Null,
    'medium' : IDL.Null,
  });
  const Time = IDL.Int;
  const Priority = IDL.Variant({
    'low' : IDL.Null,
    'high' : IDL.Null,
    'medium' : IDL.Null,
  });
  const ConsultationRequest = IDL.Record({
    'id' : IDL.Nat,
    'status' : Status,
    'sunlightExposure' : SunlightExposure,
    'stylePreference' : StylePreference,
    'balconySize' : BalconySize,
    'name' : IDL.Text,
    'email' : IDL.Text,
    'message' : IDL.Text,
    'timestamp' : Time,
    'priority' : Priority,
    'phone' : IDL.Opt(IDL.Text),
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'blockSession' : IDL.Func([IDL.Text], [IDL.Bool], []),
    'deleteConsultationRequest' : IDL.Func([IDL.Nat], [IDL.Bool], []),
    'getAllAdminSessions' : IDL.Func([], [IDL.Vec(SessionInfo)], ['query']),
    'getAllConsultationRequests' : IDL.Func(
        [],
        [IDL.Vec(ConsultationRequest)],
        ['query'],
      ),
    'getBlockedSessions' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getConsultationRequestCount' : IDL.Func([], [IDL.Nat], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'isSessionBlocked' : IDL.Func([IDL.Text], [IDL.Bool], ['query']),
    'registerAdminSession' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [IDL.Bool],
        [],
      ),
    'removeAdminSession' : IDL.Func([IDL.Text], [IDL.Bool], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'submitConsultationRequest' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Opt(IDL.Text),
          BalconySize,
          SunlightExposure,
          StylePreference,
          IDL.Text,
        ],
        [IDL.Bool],
        [],
      ),
    'unblockSession' : IDL.Func([IDL.Text], [IDL.Bool], []),
    'updateRequestPriority' : IDL.Func([IDL.Nat, Priority], [IDL.Bool], []),
    'updateRequestStatus' : IDL.Func([IDL.Nat, Status], [IDL.Bool], []),
  });
};

export const init = ({ IDL }) => { return []; };